### ISSUE TITLE
But I did it right, am I?

### ISSUE THREAD

**Issue by DarkWeBareBears69** [jigsaw-4277821/Psych-Engine-0.5.1-Android#13]
I tired to install the new version but this happened, I did what you said but it didn't work.
![Screenshot_2022-01-24-08-21-01-50_215db56658409b37716bcc56380d9440](https://user-images.githubusercontent.com/84250565/150704412-7604b20d-3fc8-4c77-9212-610a5bdf9743.jpg)
![Screenshot_2022-01-24-08-21-12-59_db51e592e420a9871f4a37915a68789b](https://user-images.githubusercontent.com/84250565/150704415-815ae632-a30e-47f5-8c51-3050ce26a0a1.jpg)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No, but is it possible to fix this?

**Comment by woaa12** [comment]
Is this 0.5.1 (in actions)? 
If it is, its not suppost to be in android/data, im pretty sure it's com.shadowmario.psychengine in storage/emulated/0

**Comment by DarkWeBareBears69** [comment]
> Is this 0.5.1 (in actions)? If it is, its not suppost to be in android/data, im pretty sure it's the "com.shadowmario.psychengine" folder in storage/emulated/0

Thanks, dude... It works.
